### ISSUE TITLE
Cannot find module 'ipc'

### ISSUE THREAD

**Issue by jt-wang** [quietshu/socket-chat-room#1]
很神奇地来提issue...   :)

使用master的最新commit, 根据文档完成操作，client server 各自 npm start 之后，前端登录界面一闪而过，进入聊天界面，所有操作不可用。查看chrome 发现如下错误: 
<img width="800" alt="2016-05-25 20 49 04" src="https://cloud.githubusercontent.com/assets/7776499/15540572/b96f800a-22ba-11e6-975a-7ec332b377eb.png">

查看 electron 文档，发现 ipc 模块应该是 electron 内置的，所以不清楚这边是怎么回事...

使用 最新 release 的 .app 文件的话，一切是正常的。

ps: 按照本repo的文档使用 npm i electron -g 的话， cannot find command 'electron'，遂去 electron 的 repo 使用 npm install electron-prebuilt -g，不知道是否影响了 ipc。

**Comment by shuding** [comment]
刚刚试了一下，确实 cannot found module 'ipc'……原因是最新的 Electron 把 API 改了：

```
require('ipc') 改成了 require('electron').ipcRenderer
ipc.on('xxx', data => {}) 改成了 ipc.on('xxx', (event, data) => {})
```

更新一下新 push 的代码应该就好（另外 electron 的包名确实是 electron-prebuilt……我搞错了）。
